import {Input, Label, Select, Slider} from '@fluentui/react-components';
import {InfoButton} from '@fluentui/react-components/unstable';
import React from 'react';
import {biasSpiralTypes} from '../../../consts/sharedConsts';
import {ConditionalPanel} from '../../Shared/ConditionalPanel';
import {BiasCoords} from './BiasCoords';


export const SpiralSpecific = ({settings, classes, handleChange, setClickAndSetProp}) => {
    return (
        <>
            <BiasCoords setClickAndSetProp={setClickAndSetProp} settings={settings} classes={classes}
                        handleChange={handleChange}/>
            <Label className={classes.label}>
                Spiral type:
                <Select
                    size="small"
                    value={settings.position.biasSpiralType}
                    className={classes.select}
                    id="position-biasSpiralType"
                    onChange={handleChange}
                >
                    {Object.values(biasSpiralTypes).map(biasSpiralType =>
                        <option
                            key={biasSpiralType.id}
                            value={biasSpiralType.id}
                        >
                            {biasSpiralType.name}
                        </option>)
                    }
                </Select>
            </Label>
            <br/>
            <ConditionalPanel active={settings.position.biasSpiralType === biasSpiralTypes.custom.id}>
                <Label className={classes.verticalLabel}>
                            <span>
                                Custom spiral formula:
                            <InfoButton content={
                                <>
                                    The spiral is generated by moving circular, with each new point making angle bigger
                                    (also this angle determines how far point is from center)
                                    <br/>
                                    This formula should determine distance from center of each point.
                                    <br/>
                                    This formula should also use only vanilla JS Math methods.
                                    <br/>
                                    Current angle of the point can be accessed as <code>angleRad</code> variable.
                                    <br/>
                                    It offers really huge variety of different spirals, feel free to experiment by
                                    trying
                                    different functions, roots, powers, trigonometric functions e.t.c
                                    <br/>
                                    Some examples: <br/>
                                    Four leaf preset formula: <code> angleRad * Math.sin(angleRad * 2)</code>
                                    <br/>
                                    Six leaf: <code>angleRad * Math.sin(angleRad * 1.5)</code>
                                    <br/>
                                    Strange tube: <code>angleRad * 4 * Math.sin(Math.pow(angleRad, 1) * 0.95)</code>
                                    <br/>
                                    Inside-outside: <code>angleRad * Math.sin(Math.pow(angleRad, 1 / 4))</code>
                                </>
                            }/>
                            </span>
                    <Input
                        className={classes.fullWidth}
                        size="small"
                        value={settings.position.biasSpiralCustom}
                        id="position-biasSpiralCustom"
                        onChange={handleChange}
                        type="text"
                    />
                </Label>
            </ConditionalPanel>
            <Label className={classes.label}>
                Spiral mult:
                <Slider
                    size="small"
                    className={classes.slider}
                    value={settings.position.biasSpiralMult}
                    id="position-biasSpiralMult"
                    onChange={handleChange}
                    min="0"
                    max="1"
                    step="0.01"
                />
                <InfoButton content={
                    <>
                        Spiral multiplier adjusts how &apos;opened&apos; the spiral looks. Basically it just
                        multiplies all distances from center. If it&apos;s small, it makes spiral more squashed
                        to
                        center.
                    </>
                }/>
            </Label>
            <Label className={classes.label}>
                Spiral thick
                <Slider
                    size="small"
                    className={classes.slider}
                    value={settings.position.biasSpiralThickness}
                    id="position-biasSpiralThickness"
                    onChange={handleChange}
                    min="0"
                    max="1"
                    step="0.01"
                />
                <InfoButton content={
                    <>
                        Allows you to adjust how many shapes &apos;thick&apos; will spiral be.
                        <br/>
                        High values will make all spiral points have many shapes instead of one.
                        <br/>
                        To see effect, adjust also spiral spread, which determine how far will those additional
                        shapes spread.
                    </>
                }/>
            </Label>
            <Label className={classes.label}>
                Spiral dens:
                <Slider
                    size="small"
                    className={classes.slider}
                    value={settings.position.biasSpiralDensity}
                    id="position-biasSpiralDensity"
                    onChange={handleChange}
                    min="0"
                    max="1"
                    step="0.01"
                />
                <InfoButton content={
                    <>
                        The spiral is generated by moving circular, with each new point making angle bigger
                        (also
                        this angle determines how far point is from center)
                        <br/>
                        Spiral density determines how much this angle will be increased with every new point.
                    </>
                }/>
            </Label>
            <Label className={classes.label}>
                Spiral spread:
                <Slider
                    size="small"
                    className={classes.slider}
                    value={settings.position.biasSpiralSpread}
                    id="position-biasSpiralSpread"
                    onChange={handleChange}
                    min="0"
                    max="1"
                    step="0.01"
                />
                <InfoButton content={
                    <>
                        Related to spiral thickness.
                        <br/>
                        Spiral spread determines how far will additional shapes created by spiral thickness
                        spread.
                        <br/>
                        This is also a parameter that depends on bias.
                        <br/>
                        High bias values will squash all additional shapes.
                    </>
                }/>
            </Label>
            <Label className={classes.label}>
                Spiral angle rand:
                <Slider
                    size="small"
                    className={classes.slider}
                    value={settings.position.biasSpiralAngleRand}
                    id="position-biasSpiralAngleRand"
                    onChange={handleChange}
                    min="0"
                    max="1"
                    step="0.01"
                />
                <InfoButton content={
                    <>
                        Related to spiral density.
                        <br/>
                        If you try to create spiral without spiral angle randomness, you will find out that it
                        looks
                        like &apos;Straight lines are coming out from the center&apos;.
                        <br/>
                        It happens because spiral density is constant, and increases angle the same every time.
                        Spiral angle randomness make it more random.
                        <br/>
                        If you wish make spiral look more organic, you may increase this parameter.
                    </>
                }/>
            </Label>
        </>
    );
};